import assert from 'node:assert/strict';
import * as physics from '../dist/ballistics.js';
import {createTerrain} from '../dist/terrain.js';
import {buildStageWorld} from '../dist/scenery.js';
assert.equal(typeof physics.traceWorld,'function','World collision must follow the actual 3D segment');
assert.equal(typeof physics.hitBody,'function','Actors must have height-aware collision');
const a={x:0,y:3,z:0},b={x:10,y:3,z:0};
const valley={height:x=>x<5?-4:-8,covers:[]};
assert.equal(physics.traceWorld({x:0,y:0,z:0},{x:0,y:0,z:0},{height:()=>0}).t,0,'A round starting inside terrain stops immediately');
assert.equal(physics.traceWorld(a,b,valley),null,'A straight shot stays above a descending valley');
const slope={height:x=>x*.5,covers:[]};
const hillside=physics.traceWorld(a,b,slope);
assert.ok(Math.abs(hillside.t-.592)<.002,'A shot intersects the rising slope at its own elevation');
const ridge={height:x=>Math.max(0,5-Math.abs(x-5)*5),covers:[]};
assert.ok(physics.traceWorld(a,b,ridge).t<.5,'Fast rounds cannot tunnel through a one-cell ridge');
const enemy={x:5,z:0,radius:.5,bottom:-5,top:-2.5};
assert.equal(physics.hitBody(a,b,enemy),null,'Passing over a lower enemy is a miss');
assert.ok(physics.hitBody(a,{x:10,y:-8,z:0},enemy)!==null,'A downhill shot can hit that same enemy');
const tower={height:()=>0,covers:[{shape:'box',x:5,y:3,z:0,sx:1,sy:6,sz:4,rotation:0}]};
assert.ok(physics.traceWorld(a,b,tower).t<.5,'Structures stop bullets');
assert.equal(physics.traceWorld({...a,y:8},{...b,y:8},tower),null,'Bullets can pass over structures');
const thin={...tower,covers:[{shape:'box',x:5,y:3,z:0,sx:.08,sy:6,sz:4,rotation:.3}]};
assert.ok(physics.traceWorld(a,b,thin),'Swept tests stop even a thin rotated beam');
const crystalWorld=buildStageWorld(createTerrain(5,7361)),crystal=crystalWorld.covers.find(c=>c.shape==='gem'&&c.sy>3);
const y=crystal.y+crystal.sy*.75;
assert.ok(physics.traceWorld({x:crystal.x-3,y,z:crystal.z},{x:crystal.x+3,y,z:crystal.z},{height:()=>-100,covers:[crystal]},0),'Crystal upper tips stop shots at their rendered full height');
assert.equal(physics.traceWorld({x:crystal.x-3,y,z:crystal.z+crystal.sz*.75},{x:crystal.x+3,y,z:crystal.z+crystal.sz*.75},{height:()=>-100,covers:[crystal]},0),null,'Empty space beside a tapered crystal does not block shots');
crystalWorld.dispose();
console.log('PASS: straight 3D trajectories, ridge/slope impacts, vertical misses, downhill hits, overhead clearance and thin structures.');
