// Security and cache headers for the Cloudflare Pages outputs (_cf/live, _cf/dev), generated from
// the FINAL HTML of each output (after the dev gate, the classic edits and the handoff pages are in
// place): every inline <script> is allowed by its SHA-256 hash, nothing else inline runs.
// Also the reader/matcher for Cloudflare's _headers and _redirects syntax, shared by the local
// server (scripts/serve-cf.mjs) and the tests, so what is tested is what Cloudflare is given.
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

// Cloudflare Pages limits: 100 header rules, 2,000 characters per line.
export const CF_MAX_RULES = 100;
export const CF_MAX_LINE = 2000;

const SCRIPT = /<script\b([^>]*)>([\s\S]*?)<\/script\s*>/gi;

/** The text of every inline <script> (no src attribute), newlines normalised as the HTML parser does. */
export function inlineScripts(html) {
  const out = [];
  for (const match of String(html).matchAll(SCRIPT)) {
    if (/\bsrc\s*=/i.test(match[1])) continue;
    out.push(match[2].replace(/\r\n?/g, '\n'));
  }
  return out;
}

export const scriptHash = text => `'sha256-${crypto.createHash('sha256').update(text, 'utf8').digest('base64')}'`;

// Features no part of Riftborn uses. Gamepad, fullscreen and autoplay stay allowed (the game uses them).
export const PERMISSIONS_POLICY = [
  'accelerometer', 'browsing-topics', 'camera', 'display-capture', 'geolocation', 'gyroscope', 'hid',
  'magnetometer', 'microphone', 'midi', 'payment', 'serial', 'usb'
].map(feature => `${feature}=()`).join(', ');

/** The Content-Security-Policy for one output, given the hashes of its inline scripts. */
export function contentSecurityPolicy({ hashes, connect }) {
  return [
    "default-src 'self'",
    ['script-src', "'self'", ...hashes].join(' '),
    // The game sets style attributes and the dev gate / classic edition carry <style> blocks.
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob:",
    "font-src 'self'",
    ['connect-src', "'self'", ...connect].join(' '),
    "media-src 'self' blob: data:",
    "worker-src 'self' blob:",
    "manifest-src 'self'",
    "object-src 'none'",
    "base-uri 'none'",
    "form-action 'self'",
    "frame-ancestors 'none'"
  ].join('; ');
}

function walk(dir, base = dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const file = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(file, base, out);
    else out.push(path.relative(base, file).split(path.sep).join('/'));
  }
  return out.sort();
}

// A content-hashed build file (js/riftborn.4339a97b57.js, css/riftborn.f62ae74eb5.css, ...).
const HASHED = /(^|\/)[^/]+\.[0-9a-f]{8,}\.(js|css|map|js\.map)$/;

/** The URL path a Pages HTML file is served at ("index.html" -> "/", "classic/index.html" -> "/classic/"). */
export function htmlUrlPath(file) {
  if (file === 'index.html') return '/';
  if (file.endsWith('/index.html')) return '/' + file.slice(0, -'index.html'.length);
  return '/' + file;
}

/**
 * Builds the _headers text for a Cloudflare Pages output directory.
 * -> { text, csp, hashes, htmlFiles }
 */
export function buildHeaders(dir, { connect, noindex = false }) {
  const files = walk(dir);
  const htmlFiles = files.filter(file => file.endsWith('.html'));
  const hashes = [...new Set(htmlFiles.flatMap(file => inlineScripts(fs.readFileSync(path.join(dir, file), 'utf8')).map(scriptHash)))].sort();
  const csp = contentSecurityPolicy({ hashes, connect });
  const lines = [
    '# Generated by scripts/build-pages.mjs from the final HTML of this output. Do not edit.',
    '/*',
    `  Content-Security-Policy: ${csp}`,
    '  Strict-Transport-Security: max-age=31536000',
    '  X-Content-Type-Options: nosniff',
    '  Referrer-Policy: strict-origin-when-cross-origin',
    `  Permissions-Policy: ${PERMISSIONS_POLICY}`,
    '  Cross-Origin-Opener-Policy: same-origin'
  ];
  if (noindex) lines.push('  X-Robots-Tag: noindex, nofollow');
  // Pages are always revalidated (a new build shows up at once); version.json is never cached (the
  // game polls it to offer updates); content-hashed bundles are cached for good.
  for (const file of htmlFiles) {
    if (file === '404.html') continue; // served for unknown paths; Pages' default revalidation applies
    lines.push(htmlUrlPath(file), '  Cache-Control: no-cache');
  }
  for (const file of files.filter(file => file === 'version.json' || file.endsWith('/version.json'))) {
    lines.push('/' + file, '  Cache-Control: no-store');
  }
  for (const file of files.filter(file => HASHED.test(file))) {
    lines.push('/' + file, '  Cache-Control: public, max-age=31536000, immutable');
  }
  const text = lines.join('\n') + '\n';
  const rules = parseHeaders(text);
  if (rules.length > CF_MAX_RULES) throw new Error(`_headers: ${rules.length} rules (Cloudflare allows ${CF_MAX_RULES})`);
  const long = text.split('\n').find(line => line.length > CF_MAX_LINE);
  if (long) throw new Error(`_headers: a line is ${long.length} characters (Cloudflare allows ${CF_MAX_LINE})`);
  return { text, csp, hashes, htmlFiles };
}

// ---- Cloudflare _headers / _redirects semantics (for serve-cf.mjs and the tests) -----------------

/** -> [{ pattern, set: [[name, value]], detach: [name] }] */
export function parseHeaders(text) {
  const rules = [];
  let rule = null;
  for (const raw of String(text).split(/\r?\n/)) {
    if (!raw.trim() || raw.trim().startsWith('#')) continue;
    if (!/^\s/.test(raw)) {
      rule = { pattern: raw.trim(), set: [], detach: [] };
      rules.push(rule);
      continue;
    }
    if (!rule) throw new Error('_headers: a header line comes before any path');
    const line = raw.trim();
    if (line.startsWith('!')) { rule.detach.push(line.slice(1).trim().toLowerCase()); continue; }
    const colon = line.indexOf(':');
    if (colon < 1) throw new Error(`_headers: not a header line: ${line}`);
    rule.set.push([line.slice(0, colon).trim(), line.slice(colon + 1).trim()]);
  }
  return rules;
}

function patternRegex(pattern) {
  // Pages patterns: "*" (splat, greedy) and ":name" placeholders (one path segment).
  let source = '';
  for (let i = 0; i < pattern.length; i++) {
    const char = pattern[i];
    if (char === '*') { source += '(.*)'; continue; }
    if (char === ':' && /[A-Za-z]/.test(pattern[i + 1] || '')) {
      while (/[A-Za-z0-9_]/.test(pattern[i + 1] || '')) i++;
      source += '([^/]+)';
      continue;
    }
    source += char.replace(/[.+?^${}()|[\]\\]/g, '\\$&');
  }
  return new RegExp('^' + source + '$');
}

/** The headers Cloudflare would attach to a path: every matching rule applies, top to bottom; a
 * header set by two rules is joined with ", " (so a policy must never be set twice). */
export function matchHeaders(rules, pathname) {
  const headers = new Map();
  for (const rule of rules) {
    if (!patternRegex(rule.pattern).test(pathname)) continue;
    for (const name of rule.detach) headers.delete(name);
    for (const [name, value] of rule.set) {
      const key = name.toLowerCase();
      headers.set(key, headers.has(key) ? { name, value: headers.get(key).value + ', ' + value, joined: true } : { name, value, joined: false });
    }
  }
  return headers;
}

/** -> [{ from, to, status }] */
export function parseRedirects(text) {
  const rules = [];
  for (const raw of String(text || '').split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const [from, to, status = '302'] = line.split(/\s+/);
    rules.push({ from, to, status: Number(status) });
  }
  return rules;
}

/** -> { location, status } or null */
export function matchRedirect(rules, pathname) {
  for (const rule of rules) {
    const match = patternRegex(rule.from).exec(pathname);
    if (!match) continue;
    let location = rule.to;
    if (rule.from.includes('*')) location = location.replace(':splat', match[1] ?? '');
    return { location, status: rule.status };
  }
  return null;
}
